#!/usr/bin/env bash
# Deploy script for uaelive.zad.tools (UAE ALIVE) on CloudPanel VPS
# Generated by skill: cloudpanel-deploy-script
set -euo pipefail

# ─── Config ───────────────────────────────────────────────
REMOTE="${REMOTE:-cp}"                       # ssh alias (root@65.108.89.49)
REMOTE_PATH="/opt/uaealive"
LOCAL_PATH="$(cd "$(dirname "$0")/.." && pwd)"
EXCLUDE_FILE="${LOCAL_PATH}/infra/.deployignore"
COMPOSE_REMOTE="docker compose -f ${REMOTE_PATH}/infra/docker-compose.prod.yml --env-file ${REMOTE_PATH}/.env"

# ─── Colors ───────────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[0;33m'; NC='\033[0m'
ok()   { echo -e "${GRN}✓${NC} $1"; }
warn() { echo -e "${YLW}!${NC} $1"; }
err()  { echo -e "${RED}✗${NC} $1" >&2; }

# ─── Args ─────────────────────────────────────────────────
DRY_RUN=0; SHOW_HELP=0; NO_BUILD=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run|-n) DRY_RUN=1; shift ;;
    --no-build)   NO_BUILD=1; shift ;;
    --help|-h)    SHOW_HELP=1; shift ;;
    *) err "Unknown arg: $1"; exit 1 ;;
  esac
done

if [[ $SHOW_HELP -eq 1 ]]; then
  cat <<EOF
Usage: infra/deploy.sh [OPTIONS]
  -n, --dry-run    Show what rsync would change, don't deploy
      --no-build   Sync files and restart without rebuilding images
  -h, --help       This help
EOF
  exit 0
fi

# ─── Pre-flight ───────────────────────────────────────────
command -v rsync >/dev/null || { err "rsync not installed"; exit 1; }
ssh -o BatchMode=yes -o ConnectTimeout=10 "$REMOTE" true 2>/dev/null \
  || { err "SSH connection to $REMOTE failed"; exit 1; }
ok "SSH OK ($REMOTE)"

ssh "$REMOTE" "test -f ${REMOTE_PATH}/.env" \
  || { err "${REMOTE_PATH}/.env missing on server — create it first (see README)"; exit 1; }
ok "server .env present"

# ─── Sync ─────────────────────────────────────────────────
RSYNC_FLAGS=(-az --delete --exclude-from="$EXCLUDE_FILE")
[[ $DRY_RUN -eq 1 ]] && RSYNC_FLAGS+=(--dry-run --itemize-changes)

ssh "$REMOTE" "mkdir -p ${REMOTE_PATH}"
rsync "${RSYNC_FLAGS[@]}" "${LOCAL_PATH}/" "${REMOTE}:${REMOTE_PATH}/"
ok "Synced → ${REMOTE}:${REMOTE_PATH}"

[[ $DRY_RUN -eq 1 ]] && { warn "dry-run only — nothing deployed"; exit 0; }

# ─── Build + restart ──────────────────────────────────────
if [[ $NO_BUILD -eq 1 ]]; then
  ssh "$REMOTE" "$COMPOSE_REMOTE up -d"
else
  ssh "$REMOTE" "$COMPOSE_REMOTE up -d --build"
fi
ok "Containers up"

# ─── Health check ─────────────────────────────────────────
sleep 5
STATUS=$(ssh "$REMOTE" "curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8080/ar" || echo "000")
if [[ "$STATUS" == "200" ]]; then
  ok "Health check: /ar → 200"
else
  err "Health check failed (/ar → ${STATUS}) — check: ssh $REMOTE '$COMPOSE_REMOTE logs --tail 50'"
  exit 1
fi
KHOR=$(ssh "$REMOTE" "curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8080/khor" || echo "000")
[[ "$KHOR" == "200" ]] && ok "Health check: /khor → 200" || warn "/khor → ${KHOR}"

ok "Deploy complete → https://uaelive.zad.tools"
