/**
 * Pure geo helpers for the WebAR experience: convert real POI coordinates
 * into compass bearings + distances from a fixed viewer standing in the
 * heart of the district, so labels can float at their true directions.
 */

import type { PoiOut } from "@/lib/types";
import { pickLocale } from "@/lib/utils";

/** Where the visitor "stands": the central sikka of Al Fahidi. */
export const VIEWER = { lat: 25.2641, lng: 55.2997 } as const;

/** Paths served from `public/` (generated by parallel tasks). */
export const PANORAMA_SRC = "/images/district-panorama.svg";
export const MARKER_PNG_SRC = "/markers/alfahidi-marker.png";
export const MARKER_MIND_SRC = "/markers/alfahidi-marker.mind";

const EARTH_RADIUS_M = 6_371_000;

function toRad(deg: number): number {
  return (deg * Math.PI) / 180;
}

/** Initial compass bearing (0-360, 0 = north) from `from` to `to`. */
export function computeBearing(
  from: { lat: number; lng: number },
  to: { lat: number; lng: number },
): number {
  const phi1 = toRad(from.lat);
  const phi2 = toRad(to.lat);
  const dLambda = toRad(to.lng - from.lng);
  const y = Math.sin(dLambda) * Math.cos(phi2);
  const x =
    Math.cos(phi1) * Math.sin(phi2) -
    Math.sin(phi1) * Math.cos(phi2) * Math.cos(dLambda);
  const theta = (Math.atan2(y, x) * 180) / Math.PI;
  return (theta + 360) % 360;
}

/** Equirectangular distance in meters — plenty accurate at district scale. */
export function distanceMeters(
  from: { lat: number; lng: number },
  to: { lat: number; lng: number },
): number {
  const x = toRad(to.lng - from.lng) * Math.cos(toRad((from.lat + to.lat) / 2));
  const y = toRad(to.lat - from.lat);
  return Math.round(Math.sqrt(x * x + y * y) * EARTH_RADIUS_M);
}

/** Signed shortest rotation from `heading` to `bearing`, in [-180, 180]. */
export function bearingDelta(bearing: number, heading: number): number {
  return ((bearing - heading + 540) % 360) - 180;
}

/** Normalize any angle into [0, 360). */
export function normalizeHeading(value: number): number {
  return ((value % 360) + 360) % 360;
}

/** A POI projected into the AR scene. */
export interface ArPoiLabel {
  slug: string;
  name: string;
  summary: string;
  kind: string;
  bearing: number;
  distance: number;
}

/**
 * Build AR labels from real POIs. Every POI keeps its true bearing — even
 * the adjacent landmarks outside the building bbox (`dubai-museum-fort`,
 * `sheikh-saeed-house`) project fine because we only need direction+distance.
 */
export function buildLabels(pois: PoiOut[], locale: string): ArPoiLabel[] {
  return pois
    .map((poi) => ({
      slug: poi.slug,
      name: pickLocale(poi.name, locale),
      summary: pickLocale(poi.summary, locale),
      kind: poi.kind,
      bearing: computeBearing(VIEWER, { lat: poi.lat, lng: poi.lng }),
      distance: distanceMeters(VIEWER, { lat: poi.lat, lng: poi.lng }),
    }))
    .sort((a, b) => a.bearing - b.bearing);
}

/** 8-wind cardinal key for a heading (message key under `live.cardinal`). */
export function cardinalKey(
  heading: number,
): "n" | "ne" | "e" | "se" | "s" | "sw" | "w" | "nw" {
  const keys = ["n", "ne", "e", "se", "s", "sw", "w", "nw"] as const;
  const index = Math.round(normalizeHeading(heading) / 45) % 8;
  return keys[index] ?? "n";
}
