"""initial schema

Revision ID: 323fc781167e
Revises: 
Create Date: 2026-07-02 22:09:51.515281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '323fc781167e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_device_id'), 'analytics_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event'), 'analytics_events', ['event'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_slug'), 'badges', ['slug'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('role_ar', sa.String(length=255), nullable=False),
    sa.Column('role_en', sa.String(length=255), nullable=False),
    sa.Column('greeting_ar', sa.String(length=1000), nullable=False),
    sa.Column('greeting_en', sa.String(length=1000), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('persona_prompt', sa.Text(), nullable=False),
    sa.Column('fallback_qa', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_slug'), 'characters', ['slug'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('description_ar', sa.String(length=2000), nullable=False),
    sa.Column('description_en', sa.String(length=2000), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('location_ar', sa.String(length=255), nullable=False),
    sa.Column('location_en', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_kind'), 'events', ['kind'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('hunt_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('poi_slug', sa.String(length=120), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('hint_ar', sa.String(length=1000), nullable=False),
    sa.Column('hint_en', sa.String(length=1000), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunt_stops_poi_slug'), 'hunt_stops', ['poi_slug'], unique=False)
    op.create_index(op.f('ix_hunt_stops_slug'), 'hunt_stops', ['slug'], unique=True)
    op.create_geospatial_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('summary_ar', sa.String(length=2000), nullable=False),
    sa.Column('summary_en', sa.String(length=2000), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('era_built', sa.String(length=120), nullable=True),
    sa.Column('wheelchair', sa.Boolean(), nullable=False),
    sa.Column('audio', sa.Boolean(), nullable=False),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_pois_geom', 'pois', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_pois_kind'), 'pois', ['kind'], unique=False)
    op.create_index(op.f('ix_pois_slug'), 'pois', ['slug'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_type'), 'submissions', ['type'], unique=False)
    op.create_table('timeline_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('description_ar', sa.String(length=2000), nullable=False),
    sa.Column('description_en', sa.String(length=2000), nullable=False),
    sa.Column('palette', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_periods_key'), 'timeline_periods', ['key'], unique=True)
    op.create_table('hunt_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['hunt_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'stop_id', name='uq_checkin_device_stop')
    )
    op.create_index(op.f('ix_hunt_checkins_device_id'), 'hunt_checkins', ['device_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=30), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('body_ar', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_audience'), 'stories', ['audience'], unique=False)
    op.create_index(op.f('ix_stories_poi_id'), 'stories', ['poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_poi_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_audience'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_hunt_checkins_device_id'), table_name='hunt_checkins')
    op.drop_table('hunt_checkins')
    op.drop_index(op.f('ix_timeline_periods_key'), table_name='timeline_periods')
    op.drop_table('timeline_periods')
    op.drop_index(op.f('ix_submissions_type'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_pois_slug'), table_name='pois')
    op.drop_index(op.f('ix_pois_kind'), table_name='pois')
    op.drop_geospatial_index('idx_pois_geom', table_name='pois', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('pois')
    op.drop_index(op.f('ix_hunt_stops_slug'), table_name='hunt_stops')
    op.drop_index(op.f('ix_hunt_stops_poi_slug'), table_name='hunt_stops')
    op.drop_table('hunt_stops')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_kind'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_characters_slug'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_badges_slug'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_analytics_events_event'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_device_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
