/**
 * POIs that have pre-rendered English narration audio at
 * /audio/pois/<slug>.en.mp3 (generated on the local GPU, tourist story only).
 * Regenerated by the asset pipeline — keep in sync with public/audio/pois/.
 */
const NARRATED_POIS: readonly string[] = [
  "al-fahidi-mosque",
  "arabian-tea-house",
  "art-alley",
  "bastakiah-nights",
  "calligraphy-house",
  "coffee-museum",
  "coins-museum",
  "creek-edge",
  "dubai-museum-fort",
  "heritage-sikka",
  "majlis-gallery",
  "old-city-wall",
  "philately-house",
  "sheikh-saeed-house",
  "smccu",
  "wind-tower-house",
  "xva-gallery",
];

export function narrationAudioSrc(
  poiSlug: string,
  locale: string,
  audience: string,
): string | undefined {
  if (locale !== "en" || audience !== "tourist") return undefined;
  return NARRATED_POIS.includes(poiSlug)
    ? `/audio/pois/${poiSlug}.en.mp3`
    : undefined;
}
